"""Contract tests for the M4 cross-engine report and failure behaviour."""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from typing import Any

import pytest


REPO_ROOT = Path(__file__).resolve().parents[3]
VALIDATION_PATH = REPO_ROOT / "tools" / "oracle" / "reference" / "run_m4_validation.py"
REPORT_PATH = REPO_ROOT / "docs" / "evidence" / "M4-oracle-sweep-report.json"


def load_validation() -> Any:
    spec = importlib.util.spec_from_file_location("chemrealm_m4_validation", VALIDATION_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_cross_engine_report_is_complete_when_present() -> None:
    if not REPORT_PATH.is_file():
        pytest.skip("local report is generated by the pinned-oracle CI command")
    report = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    assert report["schemaVersion"] == 1
    assert report["validation"]["sourceCommit"]
    assert report["validation"]["ciRun"]
    assert report["validation"]["ciHardGate"] in {True, False}
    assert "CI" in report["validation"]["executionEnvironment"]
    assert report["allPointsCompared"] is True
    assert report["pointCount"] == 10
    assert report["oracleFixtures"] == [f"ORACLE-{index}" for index in range(1, 11)]
    assert report["equivalenceSweep"] == {
        "pre": "ORACLE-7",
        "equivalence": "ORACLE-8",
        "post": "ORACLE-9",
        "postNaOHMolPerKg": 0.14,
        "note": "ORACLE-9 is a representative post-equivalence point within the declared pH comparison envelope; canonical REF-9 remains the charge-conservation acceptance fixture.",
    }
    assert {point["id"] for point in report["points"]} == set(report["oracleFixtures"])
    assert report["pass"] is True
    assert report["phreeqc"]["identityVerified"] is True
    assert report["phreeqc"]["version"] == "3.8.6-17100"
    assert report["phreeqc"]["executableSha256"]
    assert report["phreeqc"]["databaseSha256"]
    assert report["maxAbsolutePhDifference"] <= report["tolerancePh"]
    assert report["signedPhDifferenceSummary"]["allSameSign"] is True
    assert report["disagreementAnalysis"]["classification"] == "systematic-positive-offset-candidate"


def test_compare_rejects_a_missing_or_failed_engine_point() -> None:
    validation = load_validation()
    ts_rows = [{"id": "ORACLE-1", "status": "OK", "modelPh": 1.0}]
    with pytest.raises(RuntimeError, match="every oracle fixture"):
        validation.compare(ts_rows, {})

    complete_ts_rows = [
        {
            "id": f"ORACLE-{index}",
            "status": "OK",
            "modelPh": 1.0,
            "ionicStrengthMolal": 0.1,
        }
        for index in range(1, 11)
    ]
    failed_oracle = {
        f"ORACLE-{index}": {"status": "OK", "modelPh": 1.0}
        for index in range(1, 10)
    }
    failed_oracle["ORACLE-10"] = {"status": "FAIL", "modelPh": 1.0}
    report = validation.compare(complete_ts_rows, failed_oracle)
    assert report["allPointsCompared"] is True
    assert report["pass"] is False


def test_phreeqc_input_declares_molality_basis_and_named_marker() -> None:
    validation = load_validation()
    fixture = validation.load_fixture("ORACLE-8.json")
    text = validation.phreeqc_input(fixture, "equivalence.sel")
    assert "units mol/kgw" in text
    assert "-file equivalence.sel" in text
    assert "CHEMREALM_SELECTED_OUTPUT" in text
