"""The emitted JSON Schema artifacts are CONSUMED, not merely produced.

`PLAN-0001` M1's stop condition reads, verbatim:

    the JSON Schema artifact is emitted and consumed by at least one Python
    test that validates a fixture against it. That last item is what proves
    ADR-0001's "one source of truth" claim rather than asserting it.

Until this module existed, the artifacts were emitted and drift-checked —
`pnpm verify:schema-artifacts` fails if the working copy differs — but nothing
in Python read them. A drift check proves the file matches zod. It does not
prove the file is *usable*, and it cannot notice that the emitted form is
weaker than the runtime: `QuantitySchema` enforced its unit table with
`.refine()`, which zod's JSON Schema emission does not encode, so the emitted
`quantity.schema.json` accepted `{"value": 1, "unit": "furlong"}` while
`parseQuantity` rejected it. The boundary is where that class of defect lives,
which is why this test lives here and not in `contracts.test.ts`.

WHAT THIS PROVES, AND WHY EACH PART IS NEEDED
---------------------------------------------
1. Every artifact loads as draft-2020-12. Catches a malformed emission.
2. A valid fixture is ACCEPTED. Without this, a vacuously over-strict artifact
   would pass every test below.
3. An invalid fixture is REJECTED. Without this, a schema of `{}` would pass
   (1) and (2) and prove nothing.
4. Specific runtime rules survive the language boundary: an unknown unit, a
   wrong dimension, and an unknown key are refused by the ARTIFACT the same way
   the runtime refuses them.

The fixtures below are hand-written rather than generated from the TypeScript,
deliberately. A fixture generated by the same code that emits the schema would
agree with it by construction and could never detect a wrong schema.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest
from jsonschema import Draft202012Validator
from jsonschema.exceptions import ValidationError

REPO_ROOT = Path(__file__).resolve().parents[3]
ARTIFACT_DIR = REPO_ROOT / "packages" / "schema" / "json-schema"

# Mirrors FORBIDDEN_BUNDLE_FIELDS in packages/schema/src/export.ts. Duplicated
# on purpose: this is the Python side's own statement of what it refuses to
# receive, and a list imported from the artifact could not notice the list
# shrinking.
FORBIDDEN_BUNDLE_FIELDS = [
    "deviceId",
    "installId",
    "userId",
    "learnerId",
    "email",
    "phone",
    "fingerprint",
    "sessionId",
    "ipAddress",
]

# `json-schema.ts`'s `JSON_SCHEMA_SOURCES`, listed here so a contract that
# silently stops being emitted fails this test rather than going unnoticed.
EXPECTED_ARTIFACTS = [
    "quantity",
    "world-state",
    "domain-event",
    "event-log",
    "command",
    "scenario",
    "scientific-state",
    "solve-result",
    "export-bundle",
]


def load_artifact(name: str) -> dict:
    path = ARTIFACT_DIR / f"{name}.schema.json"
    assert path.is_file(), (
        f"missing artifact {path}. Run `pnpm emit:schema`. A contract that is "
        f"not emitted is invisible across the language boundary."
    )
    return json.loads(path.read_text(encoding="utf-8"))


def validator_for(name: str) -> Draft202012Validator:
    schema = load_artifact(name)
    Draft202012Validator.check_schema(schema)
    return Draft202012Validator(schema)


def is_valid(name: str, instance: object) -> bool:
    return validator_for(name).is_valid(instance)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

VALID_QUANTITY = {"value": 0.1, "unit": "mol/L"}

SOLUTE = {
    "soluteId": "HCl",
    "basis": "molarity",
    "amountConcentration": {"value": 0.1, "unit": "mol/L"},
    "molarMass": {"value": 36.4609, "unit": "g/mol"},
}

VALID_SCENARIO = {
    "schemaVersion": 3,
    "contentVersion": 1,
    "scenarioRef": "hcl-naoh",
    "title": "HCl vs NaOH",
    "materials": [
        {
            "materialId": "hcl-0.1",
            "label": "0.1000 mol/L HCl",
            "phase": "aqueous",
            "solutes": [SOLUTE],
            "density": {"value": 1.002, "unit": "kg/L"},
        }
    ],
    "vessels": [
        {
            "vesselId": "flask",
            "kind": "conicalFlask",
            "capacity": {"value": 0.25, "unit": "L"},
            "geometryRef": "flask-250",
            "position": {"unit": "mm", "x": 0, "y": 0},
            "initialContents": [
                {"materialId": "hcl-0.1", "volume": {"value": 0.025, "unit": "L"}}
            ],
        }
    ],
    "apparatus": [],
    "indicators": [],
    "modelRequirements": {
        "temperature": {"value": 298.15, "unit": "K"},
        "solvent": "water",
        "phase": "aqueous",
        "activityCorrected": True,
        "species": ["H2O", "H+", "OH-", "Cl-", "Na+"],
    },
}

SCENARIO_SNAPSHOT = {
    "scenarioRef": "hcl-naoh",
    "materials": [
        {
            "materialId": "hcl-0.1",
            "sourceDefinition": "0.1000 mol/L HCl",
            "density": {
                "value": 1.002,
                "unit": "kg/L",
                "provenance": {
                    "source": "CRC Handbook",
                    "reference": "aqueous HCl density table",
                    "category": "evaluated",
                },
            },
            "composition": [
                {
                    "soluteId": "HCl",
                    "amountConcentration": {"value": 0.1, "unit": "mol/L"},
                    "provenance": {
                        "source": "Scenario record",
                        "reference": "hcl-0.1 composition label",
                        "category": "evaluated",
                    },
                }
            ],
            "molarMasses": [
                {
                    "soluteId": "HCl",
                    "molarMass": {"value": 0.0364609, "unit": "kg/mol"},
                    "provenance": {
                        "source": "IUPAC standard atomic weights",
                        "reference": "HCl molar mass calculation",
                        "category": "calculated",
                    },
                }
            ],
            "resolvedInventoryPerLitre": {
                "waterMass": {"value": 0.998, "unit": "kg"},
                "soluteAmounts": [
                    {"soluteId": "HCl", "amount": {"value": 0.1, "unit": "mol"}}
                ],
            },
        }
    ],
    "vessels": [
        {
            "vesselId": "flask",
            "kind": "conicalFlask",
            "capacity": {"value": 0.25, "unit": "L"},
            "geometryRef": "flask-250",
            "position": {"unit": "mm", "x": 0, "y": 0},
        }
    ],
    "apparatusDefaults": [],
    "indicators": [],
    "modelRequirements": {
        "temperature": {"value": 298.15, "unit": "K"},
        "species": ["H2O", "H+", "OH-", "Cl-", "Na+"],
        "solvent": "water",
        "phase": "aqueous",
        "activityCorrected": True,
    },
}

WORLD_CREATED_EVENT = {
    "seq": 0,
    "schemaVersion": 2,
    "type": "WorldCreated",
    "payload": {
        "worldId": "w-1",
        "scenarioSnapshot": SCENARIO_SNAPSHOT,
        "contentHash": "sha256:0000",
        "solverConfig": {
            "id": "acidbase-monoprotic-davies",
            "version": "1.0.0",
            "parameters": {"Kw": 1.0e-14},
        },
        "seed": None,
    },
}

VALID_BUNDLE = {
    "format": "chemrealm.export",
    "formatVersion": 1,
    "schemaVersion": 2,
    "lineage": [
        {
            "worldId": "w-1",
            "lineage": {
                "parentWorldId": None,
                "forkSequence": None,
                "forkStateHash": None,
            },
        }
    ],
    "events": [WORLD_CREATED_EVENT],
    "includesLearnerEvidence": False,
}


# ---------------------------------------------------------------------------
# 1. Every artifact is emitted, and is a loadable draft-2020-12 schema
# ---------------------------------------------------------------------------


class TestEveryArtifactIsEmittedAndLoadable:
    @pytest.mark.parametrize("name", EXPECTED_ARTIFACTS)
    def test_loads_as_a_draft_2020_12_schema(self, name):
        validator_for(name)  # check_schema raises on a malformed emission

    @pytest.mark.parametrize("name", EXPECTED_ARTIFACTS)
    def test_declares_the_draft_it_was_emitted_as(self, name):
        assert (
            load_artifact(name)["$schema"]
            == "https://json-schema.org/draft/2020-12/schema"
        )

    def test_no_contract_is_emitted_that_this_module_does_not_know_about(self):
        """A new contract must be added here, not silently emitted.

        The Python side is the reason these artifacts exist; a contract that
        reaches the oracle without a fixture is a contract nobody validated.
        """
        on_disk = {p.name[: -len(".schema.json")] for p in ARTIFACT_DIR.glob("*.schema.json")}
        assert on_disk == set(EXPECTED_ARTIFACTS), (
            "the emitted artifact set and EXPECTED_ARTIFACTS disagree — update "
            "this list when JSON_SCHEMA_SOURCES changes"
        )


# ---------------------------------------------------------------------------
# 2 + 3. Valid fixtures accepted, invalid fixtures rejected
# ---------------------------------------------------------------------------


class TestQuantity:
    def test_accepts_a_registered_unit(self):
        assert is_valid("quantity", VALID_QUANTITY)

    def test_accepts_a_dimensionless_quantity_carrying_the_unit_one(self):
        """`{ value, unit: "1" }` — how a dimensionless quantity crosses.

        Activity, activity coefficient, mole fraction, reduced molality and
        reduced ionic strength have no unit, and before the `dimensionless`
        dimension existed the only way to send one was a bare number — the first
        exception to "a serialized quantity ALWAYS carries its unit".
        """
        assert is_valid("quantity", {"value": 0.7815, "unit": "1"})

    def test_REJECTS_an_unknown_unit(self):
        """The defect that motivated routing this through `z.enum`.

        `.refine()` is not encoded in JSON Schema, so the artifact used to
        accept this while `parseQuantity` rejected it — the runtime and the
        published contract disagreeing, which is what `ADR-0001` rule 1 exists
        to prevent.
        """
        assert not is_valid("quantity", {"value": 1, "unit": "furlong"})
        assert not is_valid("quantity", {"value": 1, "unit": "M"})

    def test_REJECTS_a_missing_unit(self):
        """No defaults: a bare number is not a quantity (AC-U3)."""
        assert not is_valid("quantity", {"value": 0.05})

    def test_the_boundary_cannot_express_finiteness_and_does_not_pretend_to(self):
        """`z.number().finite()` is a runtime guard with no JSON Schema form.

        The JSON data model has no NaN and no Infinity, so a draft-2020-12
        `"type": "number"` is finite by construction and the emission has
        nothing to add. The runtime still rejects them (`units.test.ts`,
        `contracts.test.ts`); what this records is that a reader of the
        artifact must not believe the artifact checks it.

        Asserted as the emitted form rather than as a rejection, because
        `pytest` passing a Python `float("nan")` straight to the validator
        bypasses JSON entirely and measures something the boundary never sees —
        an earlier version of this test asserted the rejection, and it failed
        for that reason rather than because the contract was wrong.
        """
        assert load_artifact("quantity")["properties"]["value"] == {"type": "number"}


class TestScenario:
    def test_accepts_a_well_formed_scenario(self):
        assert is_valid("scenario", VALID_SCENARIO)

    def test_REJECTS_a_temperature_declared_in_a_volume_unit(self):
        """Dimension coherence has to survive the boundary.

        `SerializedQuantitySchema` accepts any registered unit, so before
        `quantityOfDimension` existed the contract accepted this and the emitted
        artifact inherited the hole.
        """
        broken = copy.deepcopy(VALID_SCENARIO)
        broken["modelRequirements"]["temperature"] = {"value": 25, "unit": "mL"}
        assert not is_valid("scenario", broken)

    def test_REJECTS_a_density_declared_in_a_concentration_unit(self):
        broken = copy.deepcopy(VALID_SCENARIO)
        broken["materials"][0]["density"] = {"value": 1, "unit": "mol/L"}
        assert not is_valid("scenario", broken)

    def test_REJECTS_an_unknown_key(self):
        """Boundary shapes refuse rather than strip (ADR-0005)."""
        broken = copy.deepcopy(VALID_SCENARIO)
        broken["ka"] = 1.8e-5
        assert not is_valid("scenario", broken)

    def test_REJECTS_an_unknown_key_one_level_down(self):
        """Parity with the TypeScript side, at the depth the hole was at.

        A plain `z.object` STRIPS unknown keys while emitting
        `additionalProperties: false`, so TypeScript accepted-and-dropped what
        this validator refuses. `contracts.test.ts` has the mirror assertion on
        `SolverConfigSchema`; both must reject the same input or the "one source
        of truth" claim is false in one direction.
        """
        broken = copy.deepcopy(VALID_SCENARIO)
        broken["modelRequirements"]["surprise"] = 1
        assert not is_valid("scenario", broken)

    def test_REJECTS_a_scenario_with_no_schema_version(self):
        """`contentVersion` versions the content, `schemaVersion` the shape."""
        broken = copy.deepcopy(VALID_SCENARIO)
        del broken["schemaVersion"]
        assert not is_valid("scenario", broken)

    def test_REJECTS_the_anonymous_concentration_field(self):
        """The field a solute declared before it named its scale.

        Anti-pattern 1 of `docs/science/quantity-ontology.md`.
        """
        broken = copy.deepcopy(VALID_SCENARIO)
        solutes = broken["materials"][0]["solutes"]
        solutes[0] = {
            "soluteId": "HCl",
            "concentration": {"value": 0.1, "unit": "mol/L"},
            "molarMass": {"value": 36.4609, "unit": "g/mol"},
        }
        assert not is_valid("scenario", broken)

    def test_accepts_a_molality_basis_solute(self):
        variant = copy.deepcopy(VALID_SCENARIO)
        variant["materials"][0]["solutes"][0] = {
            "soluteId": "HCl",
            "basis": "molality",
            "molality": {"value": 0.1, "unit": "mol/kg"},
            "molarMass": {"value": 36.4609, "unit": "g/mol"},
        }
        assert is_valid("scenario", variant)

    def test_REJECTS_an_authored_dissociation_flag(self):
        """Dissociation mode belongs to the scientific component catalog."""
        broken = copy.deepcopy(VALID_SCENARIO)
        broken["materials"][0]["solutes"][0]["fullyDissociated"] = True
        assert not is_valid("scenario", broken)

    def test_accepts_multiple_molarity_basis_solutes(self):
        variant = copy.deepcopy(VALID_SCENARIO)
        variant["materials"][0]["solutes"].append(
            {
                "soluteId": "NaCl",
                "basis": "molarity",
                "amountConcentration": {"value": 0.1, "unit": "mol/L"},
                "molarMass": {"value": 58.44, "unit": "g/mol"},
            }
        )
        assert is_valid("scenario", variant)

    def test_REJECTS_multiple_molality_basis_solutes_until_joint_resolution_exists(self):
        variant = copy.deepcopy(VALID_SCENARIO)
        variant["materials"][0]["solutes"] = [
            {
                "soluteId": "HCl",
                "basis": "molality",
                "molality": {"value": 0.1, "unit": "mol/kg"},
                "molarMass": {"value": 36.4609, "unit": "g/mol"},
            },
            {
                "soluteId": "NaCl",
                "basis": "molality",
                "molality": {"value": 0.1, "unit": "mol/kg"},
                "molarMass": {"value": 58.44, "unit": "g/mol"},
            },
        ]
        assert not is_valid("scenario", variant)

    def test_REJECTS_mixed_molarity_and_molality_basis_until_joint_resolution_exists(self):
        variant = copy.deepcopy(VALID_SCENARIO)
        variant["materials"][0]["solutes"].append(
            {
                "soluteId": "NaCl",
                "basis": "molality",
                "molality": {"value": 0.1, "unit": "mol/kg"},
                "molarMass": {"value": 58.44, "unit": "g/mol"},
            }
        )
        assert not is_valid("scenario", variant)


class TestWorldGenesisSnapshot:
    def test_accepts_a_snapshot_with_tagged_scientific_inputs_and_data_provenance(self):
        assert is_valid("domain-event", WORLD_CREATED_EVENT)

    def test_accepts_separate_provenance_for_each_solute_datum(self):
        expanded = copy.deepcopy(WORLD_CREATED_EVENT)
        material = expanded["payload"]["scenarioSnapshot"]["materials"][0]
        material["composition"].append(
            {
                "soluteId": "NaCl",
                "amountConcentration": {"value": 0.1, "unit": "mol/L"},
                "provenance": {
                    "source": "Scenario record",
                    "reference": "nacl-0.1 composition label",
                    "category": "evaluated",
                },
            }
        )
        material["molarMasses"].append(
            {
                "soluteId": "NaCl",
                "molarMass": {"value": 0.05844, "unit": "kg/mol"},
                "provenance": {
                    "source": "IUPAC standard atomic weights",
                    "reference": "NaCl molar mass calculation",
                    "category": "calculated",
                },
            }
        )
        assert is_valid("domain-event", expanded)

    def test_REJECTS_bare_snapshot_composition_and_molar_mass(self):
        broken = copy.deepcopy(WORLD_CREATED_EVENT)
        material = broken["payload"]["scenarioSnapshot"]["materials"][0]
        material["composition"] = [{"soluteId": "HCl", "molPerLitre": 0.1}]
        material["molarMasses"] = [{"soluteId": "HCl", "kilogramsPerMol": 0.0364609}]
        assert not is_valid("domain-event", broken)

    def test_REJECTS_snapshot_without_density_provenance(self):
        broken = copy.deepcopy(WORLD_CREATED_EVENT)
        del broken["payload"]["scenarioSnapshot"]["materials"][0]["density"][
            "provenance"
        ]
        assert not is_valid("domain-event", broken)

    def test_REJECTS_snapshot_without_composition_provenance(self):
        broken = copy.deepcopy(WORLD_CREATED_EVENT)
        del broken["payload"]["scenarioSnapshot"]["materials"][0]["composition"][0][
            "provenance"
        ]
        assert not is_valid("domain-event", broken)

    def test_REJECTS_snapshot_without_molar_mass_provenance(self):
        broken = copy.deepcopy(WORLD_CREATED_EVENT)
        del broken["payload"]["scenarioSnapshot"]["materials"][0]["molarMasses"][0][
            "provenance"
        ]
        assert not is_valid("domain-event", broken)

    def test_REJECTS_noncanonical_units_in_resolved_snapshot(self):
        broken = copy.deepcopy(WORLD_CREATED_EVENT)
        material = broken["payload"]["scenarioSnapshot"]["materials"][0]
        material["density"]["unit"] = "g/mL"
        material["composition"][0]["amountConcentration"] = {
            "value": 100,
            "unit": "mmol/L",
        }
        material["molarMasses"][0]["molarMass"] = {
            "value": 36.4609,
            "unit": "g/mol",
        }
        material["resolvedInventoryPerLitre"]["waterMass"] = {
            "value": 998,
            "unit": "g",
        }
        material["resolvedInventoryPerLitre"]["soluteAmounts"][0]["amount"] = {
            "value": 100,
            "unit": "mmol",
        }
        assert not is_valid("domain-event", broken)

    def test_artifact_contains_no_bare_legacy_snapshot_fields(self):
        for name in ("world-state", "domain-event", "event-log", "export-bundle"):
            text = (ARTIFACT_DIR / f"{name}.schema.json").read_text(encoding="utf-8")
            assert '"molPerLitre"' not in text
            assert '"kilogramsPerMol"' not in text
        world_text = (ARTIFACT_DIR / "world-state.schema.json").read_text(encoding="utf-8")
        assert '"amountConcentration"' in world_text
        assert '"molarMass"' in world_text

    def test_REJECTS_solver_provenance_in_place_of_material_data_provenance(self):
        broken = copy.deepcopy(WORLD_CREATED_EVENT)
        broken["payload"]["scenarioSnapshot"]["materials"][0]["density"][
            "provenance"
        ] = {
            "modelId": "acidbase-monoprotic-davies",
            "modelVersion": "1.0.0",
            "activityModel": "davies",
            "category": "calculated",
            "parameters": {},
        }
        assert not is_valid("domain-event", broken)


class TestExportBundle:
    def test_accepts_a_well_formed_bundle(self):
        assert is_valid("export-bundle", VALID_BUNDLE)

    def test_the_genesis_facts_live_in_the_log_not_at_the_top_level(self):
        """The bundle must not restate what `events[0]` already carries.

        These three used to be duplicated at the top level with nothing
        checking the copies agreed.
        """
        properties = load_artifact("export-bundle")["properties"]
        for duplicate in ("scenarioSnapshot", "contentHash", "solverConfig"):
            assert duplicate not in properties, (
                f"{duplicate} is duplicated from WorldCreated.payload"
            )
        assert "events" in properties, "the log is where genesis now lives"

    def test_REJECTS_a_bundle_that_reintroduces_a_top_level_duplicate(self):
        broken = copy.deepcopy(VALID_BUNDLE)
        broken["solverConfig"] = WORLD_CREATED_EVENT["payload"]["solverConfig"]
        assert not is_valid("export-bundle", broken)

    def test_REJECTS_a_bundle_carrying_a_tracking_identifier(self):
        """AC-P4, checked against the artifact rather than the zod shape."""
        broken = copy.deepcopy(VALID_BUNDLE)
        broken["userId"] = "u-1"
        assert not is_valid("export-bundle", broken)

    def test_REJECTS_a_bundle_claiming_learner_evidence(self):
        """v1 has no evidence shape, so the only truthful answer is `false`.

        The previous schema admitted `learnerEvidence: [{...}]` with
        `passthrough()`, which accepts any key at all.
        """
        broken = copy.deepcopy(VALID_BUNDLE)
        broken["includesLearnerEvidence"] = True
        assert not is_valid("export-bundle", broken)

    def test_REJECTS_a_nested_learner_identifier(self):
        """The hole the AC-P4 test could not see, because it stopped at depth 1."""
        broken = copy.deepcopy(VALID_BUNDLE)
        broken["includesLearnerEvidence"] = True
        broken["learnerEvidence"] = [
            {"learnerId": "123", "email": "x@example.com", "sessionId": "abc"}
        ]
        assert not is_valid("export-bundle", broken)

    def test_no_forbidden_identifier_name_appears_anywhere_in_the_artifact(self):
        """Recursive, not top-level: that is the whole point of the fix."""
        text = (ARTIFACT_DIR / "export-bundle.schema.json").read_text(encoding="utf-8")
        for forbidden in FORBIDDEN_BUNDLE_FIELDS:
            assert f'"{forbidden}"' not in text

    @pytest.mark.parametrize(
        "name", ["quantity", "scenario", "export-bundle", "world-state"]
    )
    def test_the_root_refuses_unknown_keys(self, name):
        """`additionalProperties: false` must survive into the COMMITTED file.

        `contracts.test.ts` asserts the compact string `"additionalProperties"
        :false` appears, but it does so against `JSON.stringify` output. The
        committed artifact is pretty-printed with a space after the colon, so
        that assertion says nothing about the file Python actually reads. It is
        checked here against the parsed artifact instead.
        """
        assert load_artifact(name)["additionalProperties"] is False

    def test_the_bundle_fixture_is_rejected_when_required_fields_go_missing(self):
        """Guards against the fixture passing for the wrong reason."""
        broken = copy.deepcopy(VALID_BUNDLE)
        del broken["format"]
        with pytest.raises(ValidationError):
            validator_for("export-bundle").validate(broken)
