"""Contract tests for the M4 cross-engine report and failure behaviour."""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
import re
from typing import Any

import pytest


REPO_ROOT = Path(__file__).resolve().parents[3]
VALIDATION_PATH = REPO_ROOT / "tools" / "oracle" / "reference" / "run_m4_validation.py"
REPORT_PATH = REPO_ROOT / "docs" / "evidence" / "M4-oracle-sweep-report.json"
EVIDENCE_PATH = REPO_ROOT / "docs" / "evidence" / "M4.md"
GOAL_PATH = REPO_ROOT / "GOAL.md"


def evidence_matrix_rows() -> dict[str, tuple[str, str]]:
    """Return the result/evidence cells for each individually listed M4 AC."""
    rows: dict[str, tuple[str, str]] = {}
    for line in EVIDENCE_PATH.read_text(encoding="utf-8").splitlines():
        cells = [cell.strip() for cell in line.split("|")]
        if len(cells) != 5 or not cells[1].startswith("AC-S"):
            continue
        criterion = cells[1]
        if criterion in rows:
            raise AssertionError(f"duplicate acceptance-matrix row: {criterion}")
        rows[criterion] = (cells[2], cells[3])
    return rows


def load_validation() -> Any:
    spec = importlib.util.spec_from_file_location("chemrealm_m4_validation", VALIDATION_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_cross_engine_report_is_complete_when_present() -> None:
    if not REPORT_PATH.is_file():
        pytest.skip("local report is generated by the pinned-oracle CI command")
    report = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    assert report["schemaVersion"] == 1
    assert report["validation"]["sourceCommit"]
    assert report["validation"]["ciRun"]
    assert report["validation"]["ciHardGate"] in {True, False}
    assert "CI" in report["validation"]["executionEnvironment"]
    assert report["allPointsCompared"] is True
    assert report["pointCount"] == 10
    assert report["oracleFixtures"] == [f"ORACLE-{index}" for index in range(1, 11)]
    assert report["equivalenceSweep"] == {
        "pre": "ORACLE-7",
        "equivalence": "ORACLE-8",
        "post": "ORACLE-9",
        "postNaOHMolPerKg": 0.14,
        "note": "ORACLE-9 is a representative post-equivalence point within the declared pH comparison envelope; canonical REF-9 remains the charge-conservation acceptance fixture.",
    }
    assert {point["id"] for point in report["points"]} == set(report["oracleFixtures"])
    assert all(not point["id"].startswith("REF-") for point in report["points"])
    assert report["pass"] is True
    assert report["phreeqc"]["identityVerified"] is True
    assert report["phreeqc"]["version"] == "3.8.6-17100"
    assert report["phreeqc"]["executableSha256"]
    assert report["phreeqc"]["databaseSha256"]
    assert report["maxAbsolutePhDifference"] <= report["tolerancePh"]
    assert report["signedPhDifferenceSummary"]["allSameSign"] is True
    assert report["disagreementAnalysis"]["classification"] == "systematic-positive-offset-candidate"
    analysis = report["disagreementAnalysis"]
    assert analysis["attributionStatus"] == "not-isolated"
    assert {axis["id"] for axis in analysis["attributionAxes"]} == {
        "equilibrium-constants",
        "activity-coefficients",
        "species-representation",
        "water-activity",
        "basis-and-total-definition",
    }


def test_evidence_matrix_keeps_canonical_and_oracle_claims_separate() -> None:
    text = EVIDENCE_PATH.read_text(encoding="utf-8")
    ac_s1 = next(line for line in text.splitlines() if line.startswith("| AC-S1 |"))
    ac_s6 = next(line for line in text.splitlines() if line.startswith("| AC-S6 |"))
    assert "Canonical SPEC-0001 REF-1…REF-10" in ac_s1
    assert "not used as REF evidence" in ac_s1
    assert "M4-oracle-sweep-report.json" in ac_s6
    assert "ORACLE-* TS↔PHREEQC" in ac_s6
    assert "REF-9 remains" not in ac_s6


def test_m4_acceptance_matrix_is_one_row_per_criterion() -> None:
    rows = evidence_matrix_rows()
    expected = {f"AC-S{index}" for index in range(1, 17)}

    assert set(rows) == expected
    assert "AC-S10 through AC-S16" not in EVIDENCE_PATH.read_text(encoding="utf-8")
    assert all(result.strip() for result, _evidence in rows.values())
    assert all(evidence.strip() for _result, evidence in rows.values())


def test_m4_matrix_does_not_hide_already_exercised_contracts() -> None:
    rows = evidence_matrix_rows()
    result_s10, evidence_s10 = rows["AC-S10"]
    assert not result_s10.startswith("NOT RUN")
    assert "verify:scientific-math" in evidence_s10


def test_goal_separates_product_constitution_from_deployment_operator() -> None:
    text = GOAL_PATH.read_text(encoding="utf-8")
    normalized = re.sub(r"\s+", " ", text).lower()

    assert "# 10. Deployment and Governance Direction" in text
    assert "personal scientific/educational tool website" not in normalized
    assert "suitable for icp filing" not in normalized
    assert "qualified institutional operator" in normalized
    assert "scientific reality" in normalized
    assert "deployment and governance decisions belong" in normalized


def test_compare_preserves_signed_differences_when_the_offset_is_mixed() -> None:
    validation = load_validation()
    ts_rows = [
        {
            "id": f"ORACLE-{index}",
            "status": "OK",
            "modelPh": 1.0,
            "ionicStrengthMolal": 0.1,
        }
        for index in range(1, 11)
    ]
    oracle_rows = {
        f"ORACLE-{index}": {
            "status": "OK",
            "modelPh": 0.99,
            "ionicStrengthMolal": 0.1,
        }
        for index in range(1, 11)
    }
    oracle_rows["ORACLE-10"]["modelPh"] = 1.01

    report = validation.compare(ts_rows, oracle_rows)

    assert report["pass"] is True
    assert report["signedPhDifferenceSummary"]["allSameSign"] is False
    assert report["disagreementAnalysis"]["classification"] == "mixed-sign-or-insufficient-sample"
    assert report["disagreementAnalysis"]["notProven"]


def test_compare_exposes_factor_axes_without_claiming_causality() -> None:
    validation = load_validation()
    ts_rows = [
        {
            "id": f"ORACLE-{index}",
            "status": "OK",
            "modelPh": 1.01,
            "ionicStrengthMolal": 0.1,
        }
        for index in range(1, 11)
    ]
    oracle_rows = {
        f"ORACLE-{index}": {
            "status": "OK",
            "modelPh": 1.0,
            "ionicStrengthMolal": 0.1,
        }
        for index in range(1, 11)
    }

    analysis = validation.compare(ts_rows, oracle_rows)["disagreementAnalysis"]
    axes = {axis["id"]: axis for axis in analysis["attributionAxes"]}

    assert set(axes) == {
        "equilibrium-constants",
        "activity-coefficients",
        "species-representation",
        "water-activity",
        "basis-and-total-definition",
    }
    assert analysis["attributionStatus"] == "not-isolated"
    assert analysis["notProven"]
    assert all(axis["status"] for axis in axes.values())
    assert all(axis["nextControl"] for axis in axes.values())
    assert "equivalence" not in analysis["interpretation"].lower()


def test_compare_rejects_a_missing_or_failed_engine_point() -> None:
    validation = load_validation()
    ts_rows = [{"id": "ORACLE-1", "status": "OK", "modelPh": 1.0}]
    with pytest.raises(RuntimeError, match="every oracle fixture"):
        validation.compare(ts_rows, {})

    complete_ts_rows = [
        {
            "id": f"ORACLE-{index}",
            "status": "OK",
            "modelPh": 1.0,
            "ionicStrengthMolal": 0.1,
        }
        for index in range(1, 11)
    ]
    failed_oracle = {
        f"ORACLE-{index}": {"status": "OK", "modelPh": 1.0}
        for index in range(1, 10)
    }
    failed_oracle["ORACLE-10"] = {"status": "FAIL", "modelPh": 1.0}
    report = validation.compare(complete_ts_rows, failed_oracle)
    assert report["allPointsCompared"] is True
    assert report["pass"] is False


def test_phreeqc_input_declares_molality_basis_and_named_marker() -> None:
    validation = load_validation()
    fixture = validation.load_fixture("ORACLE-8.json")
    text = validation.phreeqc_input(fixture, "equivalence.sel")
    assert "units mol/kgw" in text
    assert "-file equivalence.sel" in text
    assert "CHEMREALM_SELECTED_OUTPUT" in text
